# Generated by Django 5.1.2 on 2024-12-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.PositiveBigIntegerField(db_index=True, unique=True, verbose_name='ID Telegram')),
                ('full_name', models.CharField(blank=True, max_length=250, verbose_name='Полное имя')),
                ('username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'Пользователь бота',
                'verbose_name_plural': 'Пользователи бота',
            },
        ),
        migrations.CreateModel(
            name='work_stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=250, verbose_name='Полное имя')),
                ('id_ticket', models.CharField(blank=True, max_length=250, null=True, verbose_name='ID Переоформленного тикета')),
                ('data_add', models.DateField(verbose_name='Дата добавления тикета')),
                ('count_ticket', models.IntegerField(verbose_name='Колличество')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
    ]
