# Generated by Django 5.1.2 on 2024-12-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_stats',
            old_name='data_add',
            new_name='time_of_addition',
        ),
    ]
