# Generated by Django 5.1.2 on 2025-01-05 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_data_add_work_stats_time_of_addition'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_stats',
            name='user_pk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.botuser'),
            preserve_default=False,
        ),
    ]
